# Generated by Django 5.2.6 on 2025-09-06 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('cricket', 'Cricket'), ('futsal', 'Futsal')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('current_players_count', models.PositiveIntegerField(default=1)),
                ('needed_players_count', models.PositiveIntegerField()),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
